### ISSUE TITLE
Configuring after installation throws error

### ISSUE THREAD

**Issue by orafal-dev** [holoyan/adonisjs-activitylog#5]
After updates with `uuid` I've tried installing this package, and it throws error right after I run `node ace configure @holoyan/adonisjs-activitylog` 

This is whole terminal response from the command:

```
DONE:    create database/migrations/1725662564526_create_activity_logs_table.ts
FAILED:  update adonisrc.ts file
         Could not find source file in project at the provided path: /home/ra/dev/analytics-app-backend/adonisrc.ts
```

And `adonisrc.ts` is in the path that is mentioned in the error.

**Comment by holoyan** [comment]
Is it in docker ?

**Comment by orafal-dev** [comment]
No, casual installation

**Comment by holoyan** [comment]
Hi @rafalolszewski94 
That's strange, I just use regular method provided by the [framework](https://github.com/holoyan/adonisjs-activitylog/blob/master/configure.ts#L32). 
Can you test on a fresh installed project, Ijust  tried and it worked for me.

Maybe file permission issue?

**Comment by orafal-dev** [comment]
I'll try later, for now I've added manually provider to `adonisrc.ts`
